// Code generated by "stringer --type MigrateCmd --linecomment"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Up-1]
	_ = x[UpOne-2]
	_ = x[UpTo-3]
	_ = x[Down-4]
	_ = x[DownTo-5]
	_ = x[Reset-6]
}

const _MigrateCmd_name = "upup-oneup-todowndown-toreset"

var _MigrateCmd_index = [...]uint8{0, 2, 8, 13, 17, 24, 29}

func (i MigrateCmd) String() string {
	i -= 1
	if i >= MigrateCmd(len(_MigrateCmd_index)-1) {
		return "MigrateCmd(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MigrateCmd_name[_MigrateCmd_index[i]:_MigrateCmd_index[i+1]]
}
