// Code generated by "stringer --type MigrateCmd --linecomment --output stringer.go"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Up-1]
	_ = x[UpTo-2]
	_ = x[DownTo-3]
	_ = x[Reset-4]
}

const _MigrateCmd_name = "upup-todown-toreset"

var _MigrateCmd_index = [...]uint8{0, 2, 7, 14, 19}

func (i MigrateCmd) String() string {
	i -= 1
	if i >= MigrateCmd(len(_MigrateCmd_index)-1) {
		return "MigrateCmd(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MigrateCmd_name[_MigrateCmd_index[i]:_MigrateCmd_index[i+1]]
}
